name: Step 1, Master Basic Search Syntax

# This step triggers when a comment containing "search-created" is posted on an issue
# This workflow updates from step 1 to step 2

on:
  workflow_dispatch:
  issue_comment:
    types:
      - created

permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to update the step metadata
  contents: write

jobs:
  # Get the current step to only run the main job when the learner is on the same step
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_search_created_comment:
    name: On search-created comment
    needs: get_current_step

    # We will only run this action when:
    # 1. This repository isn't the template repository
    # 2. The step is currently 1
    # 3. The comment contains "search-created"
    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == 1
          && contains(github.event.comment.body, 'search-created') }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Let's get all the branches

      # Create a few more issues for search practice
      - name: Create sample issues for search practice
        run: |
          gh issue create --title "Bug: Navigation breaks on mobile" \
                         --body "When using the app on mobile devices, the navigation menu doesn't work properly." \
                         --label "bug"
                         
          gh issue create --title "Feature request: Dark mode" \
                         --body "Would be great to have a dark mode option for the interface." \
                         --label "enhancement"
                         
          gh issue create --title "Documentation needs updating" \
                         --body "The API documentation is outdated and needs to be updated." \
                         --label "documentation"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Update to step 2
      - name: Update to step 2
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 1
          to_step: 2
